apiVersion: v1
kind: Secret
metadata:
  name: fastapi-template-secrets
type: Opaque
stringData:
  DATABASE_PASSWORD: "replace-me"
  SECRET_KEY: "replace-this-in-production"
  ALGORITHM: "HS256"
  SENTRY_DSN: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: ""
